import type { HabitInsert } from '../db/schema'

export const STARTER_HABITS: (Omit<
  HabitInsert,
  'id' | 'user_id' | 'created_at' | 'archived_at'
> & {
  displayName: string
})[] = [
  {
    displayName: 'Drink Water',
    name: 'Drink Water',
    icon: '💧',
    color: '#1D9E75',
    type: 'quantitative',
    goal_mode: 'target',
    goal_value: 8,
    goal_unit: 'glasses',
    schedule_type: 'daily',
    schedule_days: null,
    frequency_target: null,
    reminder_enabled: 1,
    reminder_time: '08:00',
    version: 1,
    version_start_date: new Date().toISOString().split('T')[0],
    share_token: null,
  },
  {
    displayName: 'Read',
    name: 'Read',
    icon: '📚',
    color: '#D85A30',
    type: 'quantitative',
    goal_mode: 'target',
    goal_value: 20,
    goal_unit: 'pages',
    schedule_type: 'daily',
    schedule_days: null,
    frequency_target: null,
    reminder_enabled: 1,
    reminder_time: '21:00',
    version: 1,
    version_start_date: new Date().toISOString().split('T')[0],
    share_token: null,
  },
  {
    displayName: 'Meditate',
    name: 'Meditate',
    icon: '🧘‍♀️',
    color: '#3B6D11',
    type: 'binary',
    goal_mode: null,
    goal_value: null,
    goal_unit: null,
    schedule_type: 'daily',
    schedule_days: null,
    frequency_target: null,
    reminder_enabled: 1,
    reminder_time: '07:00',
    version: 1,
    version_start_date: new Date().toISOString().split('T')[0],
    share_token: null,
  },
  {
    displayName: 'Exercise',
    name: 'Exercise',
    icon: '🏃‍♂️',
    color: '#854F0B',
    type: 'binary',
    goal_mode: null,
    goal_value: null,
    goal_unit: null,
    schedule_type: 'frequency',
    schedule_days: null,
    frequency_target: 3,
    reminder_enabled: 1,
    reminder_time: '07:30',
    version: 1,
    version_start_date: new Date().toISOString().split('T')[0],
    share_token: null,
  },
  {
    displayName: 'Journal',
    name: 'Journal',
    icon: '📓',
    color: '#993556',
    type: 'binary',
    goal_mode: null,
    goal_value: null,
    goal_unit: null,
    schedule_type: 'daily',
    schedule_days: null,
    frequency_target: null,
    reminder_enabled: 1,
    reminder_time: '22:00',
    version: 1,
    version_start_date: new Date().toISOString().split('T')[0],
    share_token: null,
  },
]
